M48
; DRILL file {KiCad (6.0.5)} date Thu Sep 15 01:10:38 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-15T01:10:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X8.28Y-4.69
T2
X1.12Y-1.79
X1.12Y-1.79
X1.12Y-4.67
X1.12Y-4.67
X8.26Y-1.79
X8.26Y-1.79
T0
M30
